infrastructure/modules/armonik/compute-plane.tf, infrastructure/modules/armonik/control-plane.tf
Control plane and Compute plane do not require anymore a minute to start. This PR changes the initial delay of the startup probe in order to let Kubernetes know that pods have properly started sooner.
=> Shorter startup health checks for control and compute planes

infrastructure/modules/armonik/outputs.tf, infrastructure/quick-deploy/aws/armonik/outputs.tf, infrastructure/quick-deploy/localhost/armonik/outputs.tf
`ingress` output is deprecated. Added deprecation notice to output.
=> Added deprecation notices to outputs

infrastructure/modules/monitoring/fluent-bit/fluent-bit.tf, infrastructure/modules/monitoring/fluent-bit/service-account.tf
The Kubernetes provider for terraform does not work anymore on kubernetes 1.24: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1724
This is a quick fix to make it work even without the provider fix.
-> Use plain old manifest for fluent bit SA
=> Fix for k8s 1.24

infrastructure/quick-deploy/localhost/Makefile
During installation of armonik :
Step create namespace: => you can have error message if namespaces already created.
It's not really an error but it is confusing for the user goal here is to avoid creation if namespace already created
=> Only try to create namespace if not already created

infrastructure/modules/armonik/compute-plane-confimap.tf, infrastructure/modules/armonik/control-plane-configmap.tf, infrastructure/modules/armonik/core-configmap.tf, infrastructure/modules/armonik/locals.tf, infrastructure/modules/armonik/log-configmap.tf, infrastructure/modules/armonik/polling-agent-configmap.tf, infrastructure/modules/armonik/variables.tf, infrastructure/modules/armonik/worker-configmap.tf, infrastructure/quick-deploy/aws/all/armonik.tf, infrastructure/quick-deploy/aws/all/parameters.tfvars, infrastructure/quick-deploy/aws/all/variables.tf, infrastructure/quick-deploy/aws/armonik/main.tf, infrastructure/quick-deploy/aws/armonik/parameters.tfvars, infrastructure/quick-deploy/aws/armonik/variables.tf, infrastructure/quick-deploy/aws/eks/versions.tf, infrastructure/quick-deploy/aws/monitoring/versions.tf, infrastructure/quick-deploy/aws/storage/versions.tf, infrastructure/quick-deploy/localhost/all/armonik.tf, infrastructure/quick-deploy/localhost/all/parameters.tfvars, infrastructure/quick-deploy/localhost/all/variables.tf, infrastructure/quick-deploy/localhost/armonik/main.tf, infrastructure/quick-deploy/localhost/armonik/parameters.tfvars, infrastructure/quick-deploy/localhost/armonik/variables.tf, infrastructure/quick-deploy/localhost/armonik/versions.tf, infrastructure/quick-deploy/localhost/keda/versions.tf, infrastructure/quick-deploy/localhost/metrics-server/versions.tf, infrastructure/quick-deploy/localhost/monitoring/versions.tf, infrastructure/quick-deploy/localhost/storage/versions.tf
This makes it possible to add extra configuration into all the ArmoniK configmaps. This is an easy way to adjust behavior of the deployment without needed to alter the terraform code. As an example, it integrates #834 for localhost deployment.
=> Parametrized configmaps

infrastructure/quick-deploy/aws/all/eks.tf, infrastructure/quick-deploy/localhost/all/common.tf, infrastructure/quick-deploy/localhost/all/storage.tf
All-in-one local deployments was not creating the namespace. This fixes that.
=> Fix namespaces in all-in-one deployments

infrastructure/modules/aws/ecr/ecr.tf
before dockerhub was allways pulled even if image was in local now : if image is in local we do not pull dockerhub
=> allow local images for ecr uploads

action.yml, infrastructure/modules/monitoring/fluent-bit/fluent-bit.tf, infrastructure/modules/monitoring/fluent-bit/service-account.tf, infrastructure/quick-deploy/localhost/docs/k3s.md
Fix default_secret_name is empty in service account of kubernetes 1.24 and latre
=> Fix default_secret_name is empty in service account

infrastructure/quick-deploy/aws/all/common.tf, infrastructure/quick-deploy/aws/eks/locals.tf
the creation_date tag used in all deployed resource was using a incorrect time format :
minute instead month
in date format M is for minute, m is for month
fix is to replace M => m 
if you need to test with linux command line : 
before : date +"{ creation_date: %Y/%**M**/%d %T }"
after    : date +"{ creation_date: %Y/%**m**/%d %T }"
=> fix creation date tag value : month/minute

infrastructure/modules/armonik/compute-plane-hpa.tf, infrastructure/modules/armonik/control-plane-hpa.tf, infrastructure/modules/armonik/variables.tf, infrastructure/modules/monitoring/keda/outputs.tf, infrastructure/modules/monitoring/metrics-server/outputs.tf, infrastructure/modules/onpremise-storage/mongodb/outputs.tf, infrastructure/quick-deploy/aws/all/armonik.tf, infrastructure/quick-deploy/localhost/all/armonik.tf
HPAs do not depend on Keda or prometheus. This PR adds a terraform dependency between Keda and the HPAs.
=> Add dependency to Keda

infrastructure/modules/armonik/ingress-configmap.tf, infrastructure/modules/armonik/locals.tf, infrastructure/modules/onpremise-storage/minio/locals.tf, infrastructure/modules/onpremise-storage/minio/minio.tf, infrastructure/modules/onpremise-storage/minio/outputs.tf, infrastructure/quick-deploy/localhost/all/common.tf, infrastructure/quick-deploy/localhost/all/parameters.tfvars, infrastructure/quick-deploy/localhost/all/providers.tf, infrastructure/quick-deploy/localhost/all/storage.tf, infrastructure/quick-deploy/localhost/all/variables.tf, infrastructure/quick-deploy/localhost/armonik/providers.tf, infrastructure/quick-deploy/localhost/keda/providers.tf, infrastructure/quick-deploy/localhost/metrics-server/parameters.tfvars, infrastructure/quick-deploy/localhost/metrics-server/providers.tf, infrastructure/quick-deploy/localhost/monitoring/providers.tf, infrastructure/quick-deploy/localhost/storage/locals.tf, infrastructure/quick-deploy/localhost/storage/main.tf, infrastructure/quick-deploy/localhost/storage/outputs.tf, infrastructure/quick-deploy/localhost/storage/parameters.tfvars, infrastructure/quick-deploy/localhost/storage/providers.tf, infrastructure/quick-deploy/localhost/storage/secrets.tf, infrastructure/quick-deploy/localhost/storage/variables.tf, infrastructure/utils/scripts/k8s_config.sh
related issue : [link](https://github.com/aneoconsulting/ArmoniK/issues/1040)
rem nginx config for minio http://ip.of.the.loadbalancer/minio seems impossible : https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html
"_The S3 API signature calculation algorithm does not support proxy schemes where you host either the MinIO Server API or Console GUI on a subpath, such as example.net/s3/ or example.net/console/._"
=> feat: add minio as zip storage for localhost deployment

renovate.json
This PR group renovate's PR by [datasources](https://docs.renovatebot.com/modules/datasource/).
```json
{
"matchPackagePrefixes": ["ArmoniK"],
"groupName": "release packages Armonik"
},
```
⬆️ is not needed because there is no ArmoniK package in this repo.
For security reasons, I added "helpers:pinGitHubActionDigests" in order to pin actions to a specific version.
To view an example: https://github.com/esoubiran-aneo/ArmoniK
=> chore: allow renovate to group pr by datasources

infrastructure/quick-deploy/aws/all-in-one/Makefile, infrastructure/quick-deploy/localhost/all-in-one/Makefile
When there is an error when the state is saved, the state is stored locally in `errored.tfstate` and must be manually imported into the remote backend.
This adds a make recipe to do that import and unlock the state if required.
```sh
make import-error
```
=> feat: Support import errored tfstate

infrastructure/quick-deploy/gcp/multi-stages/gar/parameters.tfvars
thoses images are wrongly used in gcp install :
- public.ecr.aws/aws-ec2/aws-node-termination-handler
- public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
- public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
- public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
=> we just remove it because it breaks the install
rem: image : amazon/aws-efs-csi-driver is still in parameters.tfvars but it does not break the install so I keeped it
=> fix: remove some unused eks images from gcp install

infrastructure/quick-deploy/gcp/all-in-one/Makefile
gke service account length limitation 
so we need to change generated RANDOM_PREFIX  from 10 to 5 random characters
=> fix: generated prefix length 10 -> 5 for gke service account

infrastructure/quick-deploy/gcp/all-in-one/common.tf, infrastructure/quick-deploy/gcp/all-in-one/gke.tf, infrastructure/quick-deploy/gcp/all-in-one/parameters.tfvars, infrastructure/quick-deploy/gcp/all-in-one/variables.tf, infrastructure/quick-deploy/gcp/multi-stages/armonik/parameters.tfvars, infrastructure/quick-deploy/gcp/multi-stages/gke/Makefile, infrastructure/quick-deploy/gcp/multi-stages/gke/main.tf, infrastructure/quick-deploy/gcp/multi-stages/gke/parameters.tfvars, infrastructure/quick-deploy/gcp/multi-stages/gke/variables.tf
objectives : 
- Do not use GKE autopilot cluster by default
- Add taints/label/toleration on different node/pods types
Here after all-in-one deployment + htcmock run results
FYI repport request :
`echo "*** NODE TAINTS BEFORE RUN : ***" && \
echo -e "Nodes Name :\tService :\tTaints :" | awk -F$'\t' '{printf "%-60s %-20s %-20s\n", $1, $2, $3}' && kubectl get nodes  -o jsonpath="{range .items[*]}{.metadata.name}{'\t'}{.metadata.labels.service}{'\t'}{.spec.taints[?(@.key == 'service')]} {'\n'}{end}"  | awk -F$'\t' '{printf "%-60s %-20s %-20s\n", $1, $2, $3}' && \
echo "*** LAUNCHING HTCMOCK TESTS : ***" && \
export grpc_endpoint=$(kubectl get services -n armonik ingress -o jsonpath={.status.loadBalancer.ingress[0].ip}) && \
docker run --rm -e GrpcClient__Endpoint=http://${grpc_endpoint}:5001 …
=> feat: GKE with taints  - nomore autopilot by default

infrastructure/modules/k8s/chaos_mesh/README.md, infrastructure/modules/k8s/chaos_mesh/main.tf, infrastructure/modules/k8s/chaos_mesh/outputs.tf, infrastructure/modules/k8s/chaos_mesh/variables.tf, infrastructure/modules/k8s/chaos_mesh/versions.tf, infrastructure/quick-deploy/gcp/all-in-one/chaos-mesh.tf, infrastructure/quick-deploy/gcp/all-in-one/gar.tf, infrastructure/quick-deploy/gcp/all-in-one/outputs.tf, infrastructure/quick-deploy/gcp/all-in-one/variables.tf, infrastructure/quick-deploy/localhost/all-in-one/chaos-mesh.tf, infrastructure/quick-deploy/localhost/all-in-one/outputs.tf, infrastructure/quick-deploy/localhost/all-in-one/variables.tf, versions.tfvars.json
**added Chaos Mesh**
I created :
- infrastructure/modules/k8s/chaos-mesh
- infrastructure/quick-deploy/{localhost,gcp}/all-in-one/chaos-mesh.tf
Updated : 
- infrastructure/quick-deploy/{localhost,gcp}/all-in-one/{variables,outputs}
- versions.tfvars.json
_Would be good to do a squash merge_
=> feat: add chaos mesh infra

infrastructure/quick-deploy/aws/storage.tf, infrastructure/quick-deploy/aws/variables.tf
linked to infra pr : [link](https://github.com/aneoconsulting/ArmoniK.Infra/pull/105)
As described in the official Redis documentation :
Redis LRU eviction is not a perfect LRU but use sampling : [link](https://redis.io/docs/reference/eviction/#approximated-lru-algorithm)
=> during the eviction process by default batchs of 5 random keys are challenged and the oldest one is removed
=> This can lead to data loss in our running job.
Depending of the user workload it can be helpful to expose the sampling number in the configuration of redis/elasticache
It will not fix the problem, but it will reduce the frequency of its occurrence.
test validation screenshot on AWS
=> feat: expose max_memory_samples parameter for redis/elasticache

infrastructure/quick-deploy/aws/storage.tf, infrastructure/quick-deploy/aws/variables.tf, infrastructure/quick-deploy/gcp/storage.tf, infrastructure/quick-deploy/gcp/variables.tf, infrastructure/quick-deploy/localhost/storage.tf, infrastructure/quick-deploy/localhost/variables.tf, tools/access-mongo-as-admin.sh, tools/access-mongo-as-user.sh, tools/access-mongo-from-kubernetes-as-user.sh, versions.tfvars.json
This pull request aims to modify the way the mongodb module is called in the quick-deploy modules (aws, gcp and onpremise/localhost) following this PR in the ArmoniK.Infra repo : https://github.com/aneoconsulting/ArmoniK.Infra/pull/140
It adds the two attributes `helm_chart_repository` and `helm_chart_version` that are now needed to call the mongodb module, and it also changes the default value for the mongodb image used, from `mongo` to `bitnami/mongodb`, as the refactored module was developed with the intent to use the latter image.
Additionnaly, it modifies the versions.tfvars.json file to use the adequate version of ArmoniK.Infra, refactoring the maps `armonik_images.image_tags` and `armonik_images.helm_charts` for the deployment to retrieve the correct mongodb image and helm chart to …
=> refactor: adapt quick-deploy for refactored mongodb module

infrastructure/quick-deploy/aws/parameters.tfvars, infrastructure/quick-deploy/aws/storage.tf, versions.tfvars.json
This PR intends to fix the AWS deployment which was broke by https://github.com/aneoconsulting/ArmoniK/pull/1293 .
The break happened to be caused an incapacity of defining a custom volume provisionning mechanism or of disabling persistence. The Helm chart used to define a storage class based on an EBS provisionner which is not automatically present in the EKS.
This PR integrates the fix on [ArmoniK.Infra](https://github.com/aneoconsulting/ArmoniK.Infra) introduced by https://github.com/aneoconsulting/ArmoniK.Infra/pull/153 .
=> fix: Fix AWS deployment

infrastructure/quick-deploy/localhost/common.tf, infrastructure/quick-deploy/localhost/variables.tf
This PR is to fix the minio default bucket name from `minioBucket` which is not conforming to the Bucket naming rules (https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) leading to `The specified bucket is not valid` error.
=> fix: change minio default bucket name

.github/workflows/deploy.yml
With the new version of K3s, the folder `/var/log/pods` is created with the permissions 0750, instead of 755 like before.
The copy was using `sudo cp -rL /var/log/pods/armonik_* DEST` which would make the shell do the expansion, but without the right permissions (because the shell is not ruinning as root).
The fix is just to perform a find as root to do the copy.
=> fix: pipeline logs

infrastructure/quick-deploy/aws/parameters.tfvars, infrastructure/quick-deploy/aws/variables.tf
**Description of the Changes:**
This update introduces a new node group specifically designed for running ArmoniK workers on GPU instances. Key changes include:
- **GPU Node Group Creation:** A new gpu_workers node group is added, configured to run on NVIDIA GPU instances (g4dn.xlarge) using the Bottlerocket AMI. Taints and labels are applied to ensure that only GPU-specific workloads are scheduled on these nodes.
- **GPU Workload Partition:** A new gputest partition is introduced, which directs workloads requiring GPU acceleration to the gpu_workers node group. This includes setting resource requests and limits tailored for GPU tasks.
- **Changed Resource Definitions:** The structure of resource limit and request definitions for compute plane workers has been changed to fit the request …
=> feat: Armonik with GPU acceleration on AWS

infrastructure/quick-deploy/gcp/keda.tf, infrastructure/quick-deploy/gcp/variables.tf, versions.tfvars.json
Deployments of newer versions of keda fail
A variable has been introduced in the keda chart helm with default value to ghcr.io. We need to expose this variable in our deployment so that we can update it when dealing with private registries. Also the default variable for the keda chart helm version was used. The used of the defined version needs to be fixed.
=> fix: keda variable issues

infrastructure/quick-deploy/aws/Makefile, infrastructure/quick-deploy/gcp/Makefile
When deploying on AWS or GCP, the upload of the images can take a long time, or might even fail because of docker rate limit.
Add a `hibernate` command to the Makefile in order to destroy all the expensive resources (compute, redis, queue), but keep inexpensive resources, and especially keep the images in the private registry.
Deploying after an hibernate works as intended on AWS. GCP has not been testing yet.
When hibernate is used, the following deployment is much faster because the images are already there. Hibernate leaves some resources around.
=> chore: Add hibernate option to destroy a deployment but keep images

tools/force-delete-namespace.sh
Sometimes, when destruction goes wrong, the kubernetes namespace might end up being undeletable by conventional means. In those cases, even `kubectl delete namespace NAME --force --grace-period=0` does nothing.
Add a script to remove all the finalizers of the namespace to tell kubernetes that the namespace has now been finalized.
This script should be used only as a last resort as it might leave resources alive.
=> chore: add script to force delete a namespace

tools/metrics/README.md, tools/metrics/export/export-prometheus-s3.sh, tools/metrics/export/prom-export.yml, tools/metrics/import/configs/grafana.yml, tools/metrics/import/configs/prometheus.yml, tools/metrics/import/docker-compose.yml, tools/metrics/import/import-prometheus-s3.sh
Prometheus metrics are usually lost after ArmoniK infra gets destroyed. This PR includes scripts to save this data so it can be looked at and analyzed later on.
This PR introduces a script that can be ran to export the data from Prometheus into an S3 bucket (at the end of github workflows for example). Along with a minimal monitoring deployment that current just includes Grafana and Prometheus, with a script that can be used to quickly import back previous Prometheus data into this deployment so it can be studied/analyzed.
Scripts were tested on both local and AWS deployments.
Not relevant. 
Check README.md for additional information.
=> feat: Prometheus metrics export and import

tools/metrics/export/export-mongodb-s3.sh, tools/metrics/export/mongo-export.yml
To further our ability to analyze the behavior of ArmoniK, this PR introduces a script to export TaskData (and later on other MongoDB collections) to an S3 bucket. They can be importer later on onto another MongoDB setup using mongo-tools (a separate PR with a script for that) or ideally just work with the JSON file directly or using a smaller database (such as TinyDB) to analyze the data.
This PR introduces a shell script and a kubernetes job that makes use of Sling to export MongoDB data to an S3 bucket. 
Tested on both an AWS and localhost deployment of ArmoniK.
Not Applicable.
None.
=> feat: Added script and kubernetes job to export mongodb collections to S3

infrastructure/quick-deploy/aws/Makefile, infrastructure/quick-deploy/gcp/Makefile, infrastructure/quick-deploy/localhost/Makefile
Running `make deploy` sometimes fails at the `get-modules` stage because of internet speed, and takes a long time to run.
Instead of fetching the entire ArmoniK.Infra repository (which can take a long time), we fetch only the latest commit of the version we're trying to use.
Deployed ArmoniK with it on localhost, but it should be the same for aws/gcp.
Slightly faster deployment on slower internets.
None.
=> fix: Changed clone depth of get-modules to 1

infrastructure/quick-deploy/gcp/parameters.tfvars, infrastructure/quick-deploy/gcp/storage.tf, infrastructure/quick-deploy/gcp/variables.tf, infrastructure/quick-deploy/localhost/parameters.tfvars, infrastructure/quick-deploy/localhost/storage.tf, infrastructure/quick-deploy/localhost/variables.tf
Based on the new feature introduced by https://github.com/aneoconsulting/ArmoniK.Infra/pull/153, this PR enables different persistence configuration for both localhost and GCP deployments, as it is already done for AWS.
It includes a new object persistent_volume in the mongodb variable. If it is null, persistence is disabled as it was before, else, persistence is enabled under the condition that the configuration provided fits you cluster.
Deployed on GCP and localhost.
More flexibility with MongoDB persistence for GCP and localhost.
=> feat: Parametrization of MongoDB persistence for localhost and GCP

.github/workflows/bench-benchmark.yml, benchmarking/aws/2-21-0_8e69cdd2f5ca8dd99652ce651bc4ff9eaa8776eb/parameters.tfvars, benchmarking/aws/2-21-0_8e69cdd2f5ca8dd99652ce651bc4ff9eaa8776eb/versions.tfvars.json, benchmarking/aws/README.md, benchmarking/aws/parameters.tfvars, tools/ci/bench-job-template.yml, tools/ci/python/program.py, tools/ci/python/requirements.txt
Related to ArmoniK benchmarking automation project, [Bench application](https://github.com/aneoconsulting/ArmoniK.Core/tree/main/Tests/Bench) is the most suited one for testing the ArmoniK's sheer orchestration performance
Use [Bench action from Armonik.Action.Deploy](https://github.com/aneoconsulting/Armonik.Action.Deploy/pull/23) to benchmark ArmoniK with Bench application on localhost on each commit on main, and on AWS at each release.
There's also a possibility to launch this workflow manually, with an option to choose whether the infrastructure must be automatically destroyed after the session is finished. This can be useful to perform post-mortem analysis.
It introduces a Python script that is meant to retrieve the throughput of a session and return a JSON containing its value.
It …
=> feat: add bench workflow for AWS

infrastructure/quick-deploy/aws/armonik.tf, infrastructure/quick-deploy/aws/storage.tf
SQS was added to ArmoniK.Core but was never supported in ArmoniK.Infra, now that SQS is added as a module to ArmoniK.Infra. This PR makes adjustments to ArmoniK to support these upcoming changes;
Created instances of the SQS module/service account and made it toggleable through a variable. Since integrating SQS required creating a service account that will be used by ArmoniK's control and compute planes.
Tested, queue is being created, used and tasks are executed in ArmoniK.
TODO.
Not Applicable.
=> feat: Added SQS support to ArmoniK

infrastructure/quick-deploy/aws/Makefile, infrastructure/quick-deploy/gcp/Makefile, infrastructure/quick-deploy/localhost/Makefile
Can be useful for debugging Terraform.
Simply adds a make rule to use command `terraform console` with the appropriate Terraform state.
Very easy to test, just needs a relevant Terraform state to work efficiently for debugging deployments.
Can improve our capacity to debug tricky Terraform issues.
The rule `make console` holds a lock on Terraform state (through `terraform console` command), which means the rule cannot be used while the state is being modified and vice-versa.
=> feat: add "console" rule in Makefile

infrastructure/quick-deploy/aws/Makefile, infrastructure/quick-deploy/gcp/Makefile, infrastructure/quick-deploy/localhost/Makefile
Shallow clone of the infra (https://github.com/aneoconsulting/ArmoniK/pull/1342) introduced a bug where it is impossible to change branch after the first `make get-modules`.
Add option in clone to avoid locking the remote to a single branch/tag.
This has been tested locally by removing the `generated/infra-modules` folder, calling `make get-modules`, modifying the infra version, and recalling `make get-modules`.
This fix only works if the infra has not been fetched yet.
If you have already fetched the infra by calling make, you can either remove the `generated/infra-modules` folder,
or calling the following command from the `generated/infra-modules` folder:
```sh
git remote set-branches origin '*'
```
=> fix: Avoid locking Infra to a single tag

infrastructure/quick-deploy/localhost/armonik.tf
Implement RabbitMQ module in the core configurations for **localhost** in order to deploy ArmoniK, 
The module RabbitMQ was missing in the Core configuration and we were unable to deploy Armonik using RabbitMQ as queue
Tested locally and htcmock tests were ran.
Ability to use RabbitMQ as queue to deploy Armonik locally.
None
=> fix: add RabbitMQ module to core configurations in Armonik deployment

infrastructure/quick-deploy/aws/Makefile, infrastructure/quick-deploy/gcp/Makefile, infrastructure/quick-deploy/localhost/Makefile
Need a way to tell the user to export the generated config file path for the ArmoniK CLI.
Changed previous commands to signal for this, and added a fix for the SAN.
Tested locally.
Not applicable.
Requires [#208](https://github.com/aneoconsulting/ArmoniK.Infra/pull/208) to be merged.
=> feat: Added hint to export CLI config

infrastructure/quick-deploy/aws/Makefile, infrastructure/quick-deploy/gcp/Makefile, infrastructure/quick-deploy/localhost/Makefile
The command `git fetch` does not fetch anything if the source is a tag.
Use the command `git fetch tag` to fetch the right infra version, and fallback to `git fetch` in case the `MODULE_VERSION` is not a tag but a branch.
Works as expected.
This is a continuation of https://github.com/aneoconsulting/ArmoniK/pull/1367
=> fix: Fetch tag in make get-modules

.docs/content/getting-started/execution/how-to-launch-HelloWorld-Sample.md, .docs/content/user-guide/how-to-configure-partitions.md
Previously, some documentation links were unavailable or broken.
The links for "How to launch HelloWorld" and "How to configure partition" files now use relative paths pointing to the correct local files, replacing the previous GitHub repository URLs.
=> docs: add correct for helloworld sample and partition doc

infrastructure/quick-deploy/localhost/parameters.tfvars, infrastructure/quick-deploy/localhost/storage.tf, infrastructure/quick-deploy/localhost/variables.tf
Persistence is not enabled by default on Localhost.
Expose persistence option for sharding, and make persitence the default.
This has been tested locally. Data remains available even if pods are deleted manually, or if the helm chart is updated to a compatible version (same minor), or if the mongodb image is updated.
=> fix: Enable MongoDB persistence by default on Localhost

infrastructure/utils/scripts/installation/prerequisites-installer.sh, infrastructure/utils/scripts/installation/prerequisites/install-docker.sh, infrastructure/utils/scripts/installation/prerequisites/install-dotnet.sh
Make the installation more robust.
- Remove dotnet installation as it not needed anymore to run samples shown in documentation. We use docker now.
- Check if docker is already installed before trying to install to avoid conflict between docker packages during installation.
- The installation script was run on my machine and seems to work properly.
=> fix: remove dotnet 6 install and install docker only if not available

infrastructure/quick-deploy/aws/parameters.tfvars, infrastructure/quick-deploy/gcp/parameters.tfvars, infrastructure/quick-deploy/localhost/parameters.tfvars
With the first version of PymoniK out. This PR aims to add pymonik partitions that use the latest available worker image. This would make it easier to get up and running with PymoniK (`make deploy` on localhost and then directly run your PymoniK code without additional work)
Added partitions that use the `harmonic_snake` worker image for the different reference deployments.
Local deployment works, AWS was also tested, it should probably also work for GCP. 
Make it easier to get up and running with PymoniK.
This needs the PR on floating tags to be merged into the PymoniK repo in addition to creating a new PymoniK release.
=> feat: Added pymonik partitions to the reference deployments

infrastructure/quick-deploy/aws/parameters.tfvars
On AWS, the pod deletion cost updater had no node-selector, and was therefore deployed onto the others node pool.
Deploy the pdc-updater with the node selector `{ service = "metrics" }`
Deploying on AWS works.
Deployment should be cheaper because the `metrics` node will host the pdc-updater. It would also make the deployment more reliable during the destruction by avoiding network interfaces that are not destroyed with their nodes from the `others` pool.
=> fix: Add node-selector for pdc-updater

infrastructure/quick-deploy/aws/armonik.tf, infrastructure/quick-deploy/aws/storage.tf
S3 output was not passed to armonik, and the read/write permissions on the bucket were not given to the right role.
Propagate the S3 module output to armonik.
Give the permission to the role that is bound to the kubernetes service account given to core.
Deploying with S3 and SQS is working as expected. It even works updating a deployment from Redis to S3.
=> fix: Propagate S3 configuration and fix permissions

README.md
Repair broken links in documentation
Replace broken link to installation by a link to getting started
=> docs: replace broken link by getting started

infrastructure/quick-deploy/aws/versions.tf, infrastructure/quick-deploy/gcp/versions.tf, infrastructure/quick-deploy/localhost/versions.tf
Helm provider has been updated to plugin framework, and removed blocks from provider configuration.
It appears that this new version is not yet stable enough: https://github.com/hashicorp/terraform-provider-helm/issues/1637
Restrict the helm provider version to `~> 2.17.0`
=> fix: Restrict Helm provider version

infrastructure/quick-deploy/aws/Makefile, infrastructure/quick-deploy/gcp/Makefile, infrastructure/quick-deploy/localhost/Makefile
Shell expansion in make are done every time a variable is called, making it slow for gcp deployment where a gcloud command is called every time the project is needed.
All shell commands in variables have been changed to be eagerly evaluated instead of lazily.
Make commands work locally, and are faster (especially  gcp, where make get-modules went from 1.7s to 1s).
Behavior of make is the same.
=> chore: Avoid calling shell multiple times in make

.docs/content/getting-started/installation/kubernetes.md, infrastructure/quick-deploy/aws/Makefile, infrastructure/quick-deploy/gcp/Makefile, infrastructure/quick-deploy/localhost/Makefile
When working on custom infra, it can be interesting to disable the fetching of the infra modules, and thus keep extra commits that have been added to ArmoniK.Infra
If MODULES_VERSION is empty, skip fetching of the modules. If the folder MODULES_DIR does not exit and MODULES_VERSION is empty, an error is raised.
Also force the clone of a single branch, but reenable fetching other branches later on.
All the combination of make get-modules sequence have been tested and works as expected.
=> chore: Allow empty MODULES_VERSION

infrastructure/quick-deploy/gcp/common.tf
When using my username as a prefix for the GCP ArmoniK deployment, I encountered a duplicate error, as if the prefix already existed.
Added a `toset` to avoid duplicate errors when applying a username as a prefix.
Tested by deploying with my username as a prefix — deployment succeeded without errors.
Users can now safely use their username as a prefix for GCP ArmoniK deployments.
=> fix: use username as prefix is valid now
