infrastructure/quick-deploy/localhost/README.md

Insert a couple of dependencies such that the described installation runs smoothly

add two more dependencies

---

docs/Happy Flow Diagram Sequence

Add sequence diagram for happy flow scenario
Diagram should be generated with https://sequencediagram.org/

Create Happy Flow Diagram Sequence

---

infrastructure/quick-deploy/localhost/README.md

New url for seq using ingress load balancer in ArmoniK 2.7

[Install Guide] New url for seq in ArmoniK 2.7

---

CHANGELOG.md
README.md
armonik-versions.txt

V2.7.2 pre

---

infrastructure/modules/armonik/admin-gui.tf

Allows Admin GUI to interact with the control plane

Add control plane URL in GUI pod

---

infrastructure/quick-deploy/aws/ecr/parameters.tfvars

Fix the docker image names for admin gui

Fix docker images for admin gui

---

tools/export-mongo.sh

Create a script to export the mongodb table from ArmoniK to a local drive (use full for the GUI)

chore(tools): create export db script

---

CHANGELOG.md
infrastructure/quick-deploy/aws/ecr/parameters.tfvars
infrastructure/quick-deploy/aws/monitoring/parameters.tfvars
infrastructure/quick-deploy/localhost/monitoring/parameters.tfvars

Upgrade Fluent-bit tag

---

.gitignore
infrastructure/utils/scripts/armonik_dev_environment.ps1
infrastructure/utils/scripts/shell/armonik_installation.sh
infrastructure/utils/scripts/shell/armonik_requirements.sh
infrastructure/utils/scripts/shell/test_armonik.sh
infrastructure/utils/scripts/shell/ubuntu_requirements.sh

Update script powershell and associated bash scripts for WSL deployment.

---

CHANGELOG.md

Update CHANGELOG.md to mention version v2.8.4

---

infrastructure/quick-deploy/aws/armonik/parameters.tfvars
infrastructure/quick-deploy/localhost/armonik/parameters.tfvars

Remove the multiple partitions in quick-deploy examples.

Remove multiple partitions in quick-deploy

---

armonik-versions.txt
infrastructure/quick-deploy/aws/armonik/parameters.tfvars
infrastructure/quick-deploy/aws/ecr/parameters.tfvars
infrastructure/quick-deploy/aws/monitoring/parameters.tfvars
infrastructure/quick-deploy/localhost/armonik/parameters.tfvars
infrastructure/quick-deploy/localhost/monitoring/parameters.tfvars

Update core to its current latest release

Update core to 0.6.2 everywhere

---

infrastructure/docs/client-node/cloud-init-templates/0009-k3s.yaml
infrastructure/docs/client-node/cloud-init-templates/0013-copyfile.yaml
infrastructure/docs/client-node/cloud-init-templates/0014-hostname.yaml
infrastructure/docs/client-node/cloud-init.tf
infrastructure/docs/client-node/data/kubectl-cheat-sheet.md
infrastructure/docs/client-node/instances.tf
infrastructure/docs/client-node/outputs.tf
infrastructure/docs/client-node/parameters.tfvars
infrastructure/docs/client-node/providers.tf
infrastructure/docs/client-node/security-group.tf
infrastructure/docs/client-node/ssh_key.tf
infrastructure/docs/client-node/variables.tf
infrastructure/docs/client-node/vpc.tf

Customized EC2 for armonik clients

Customized client ec2 for armonik

---

action.yml

Fixed warning appearing in ExtCsharp due to this action.yml

---

docs/Partitionning.md
infrastructure/quick-deploy/aws/armonik/main.tf
infrastructure/quick-deploy/aws/armonik/parameters.tfvars
infrastructure/quick-deploy/aws/armonik/variables.tf
infrastructure/quick-deploy/localhost/armonik/main.tf
infrastructure/quick-deploy/localhost/armonik/variables.tf

Partitionning

---

infrastructure/utils/scripts/armonik_dev_environment.ps1
infrastructure/utils/scripts/shell/systemd_wsl.sh
infrastructure/utils/scripts/shell/ubuntu_requirements.sh

- Fixed dev env install script to account for the default version change
- Added the option to change the virtual disk path
- TODO in future PR : Add option to change ubuntu version (with proper support)
- TODO in future PR : Fix issues regarding conflicting services (instead of disabling them)
- TODO in future PR : Add support for W11 native systemd support

Fix dev env install script to account for the default version change

---

CHANGELOG.md

Add link to buffer submission in the changelog

Update link for buffer submit

---

infrastructure/quick-deploy/aws/all/armonik.tf
infrastructure/quick-deploy/aws/all/parameters.tfvars
infrastructure/quick-deploy/aws/all/storage.tf
infrastructure/quick-deploy/aws/all/variables.tf
infrastructure/quick-deploy/localhost/all/armonik.tf
infrastructure/quick-deploy/localhost/all/common.tf
infrastructure/quick-deploy/localhost/all/parameters.tfvars
infrastructure/quick-deploy/localhost/all/storage.tf
infrastructure/quick-deploy/localhost/all/variables.tf
versions.tfvars.json

The all-in-one deployments were not updated after the S3 object storage implementation. This PR fixes it.

Fix all in one for S3 object storage

---

infrastructure/modules/armonik/locals.tf
infrastructure/modules/armonik/secrets.tf
infrastructure/quick-deploy/aws/all/monitoring.tf
infrastructure/quick-deploy/aws/armonik/parameters.tfvars
infrastructure/quick-deploy/aws/monitoring/secrets.tf
infrastructure/quick-deploy/localhost/all/monitoring.tf
infrastructure/quick-deploy/localhost/monitoring/secrets.tf

Fix HPA for compute-plane with adding the Prometheus server address.

Add secret for prometheus

---

.github/workflows/deploy.yml
action.yml

Fix installation of terraform, docker, aws and kubectl.
check if the binaries exit, we don't install else we install them.

Fixed terraform,docker,aws,kubectl installation

---

infrastructure/quick-deploy/localhost/all/variables.tf

node exporter image has been updated

fix node exporter deployment in "all in one" local

---

CHANGELOG.md
armonik-versions.txt
infrastructure/quick-deploy/aws/armonik/parameters.tfvars
infrastructure/quick-deploy/aws/ecr/parameters.tfvars
infrastructure/quick-deploy/aws/monitoring/parameters.tfvars
infrastructure/quick-deploy/localhost/armonik/parameters.tfvars
infrastructure/quick-deploy/localhost/monitoring/parameters.tfvars
versions.tfvars.json

Update code to 0.9.2 to fix metrics exporter

Fix: Too many queries from metrics exporter

---

infrastructure/quick-deploy/aws/all/parameters.tfvars
infrastructure/quick-deploy/aws/eks/parameters.tfvars

Update eks from 1.24 to 1.25
fix : #912

update eks from 1.24 to 1.25

---

.github/workflows/deploy.yml
infrastructure/quick-deploy/localhost/all/parameters.tfvars

ci: Update local host pipeline to use all in one deployment

---

infrastructure/quick-deploy/aws/all/common.tf

[infos](https://github.com/aneoconsulting/ArmoniK/issues/950)

creation_date must be known at plan time

---

.docs/test_plan.md

docs: add test plan

---

CHANGELOG.md
infrastructure/modules/aws/s3/s3.tf
infrastructure/quick-deploy/aws/ecr/parameters.tfvars

fix image tag of the worker in the ecr deployment

Yk/pre 2.10.4

---

.docs/content/3.benchmarking/0.test-plan.md
.docs/content/3.benchmarking/_dir.yml
.docs/content/3.benchmarking/benchmarking-armonik-v2.10.4.md
.docs/content/3.benchmarking/benchmarking-armonik-v2.10.5.md
.docs/content/3.benchmarking/benchmarking-armonik-v2.12.3.md
.vscode/extensions.json

- fix typos
- rename files in order (https://aneoconsulting.github.io/armonik-docs-theme/guide/content-directory#filename)
- rework headers levels for a better semantic

docs: rename and fix typos in benchmarking

---

.docs/content/1.installation/1.linux/0.prerequisites.md
.docs/content/1.installation/1.linux/1.installation.md
.docs/content/1.installation/1.linux/2.verify-installation.md
.docs/content/1.installation/1.linux/3.deploy-script.md
.docs/content/1.installation/2.windows/0.installation-using-wsl2.md
.docs/content/1.installation/2.windows/1.wsl2-with-systemd.md
.docs/content/1.installation/2.windows/2.wsl2-with-genie.md
.docs/content/1.installation/2.windows/3.useful-commands-for-wsl2.md
.docs/content/1.installation/3.aws/aws-deployment-using-k3s.md
.docs/content/1.installation/3.aws/aws-deployment-using-kubeadm.md
.docs/content/2.guide/1.how-to/how-to-configure-authentication.md
.docs/content/2.guide/1.how-to/how-to-configure-seq.md

In order to show to user where the command must be copy, I added the name of the terminal.

docs: add terminal into code blocks

---

.docs/content/2.guide/populate-database.md
tools/mongodb/clean-all.sh
tools/mongodb/scripts/clean-all.js

This script a useful in dev mode to avoid to destroy deployment to clean the database.
To avoid unfortunate execution, I added 2 questions:
- Are you sure?
- Do you want a backup?

feat: add a script to drop db

---

tools/wsl_installation/armonik_dev_environment.ps1
tools/wsl_installation/shell/armonik_installation.sh
tools/wsl_installation/shell/armonik_requirements.sh
tools/wsl_installation/shell/systemd_wsl.sh
tools/wsl_installation/shell/test_armonik.sh
tools/wsl_installation/shell/ubuntu_requirements.sh

This PR is important to keep a script which allow to demonstrate ArmoniK quickly

chore: Re-add powershell script for ArmoniK deployment on WSL (Ubuntu 22.04)

---

.docs/content/2.guide/differentiate-environments.md
infrastructure/quick-deploy/aws/all-in-one/armonik.tf
infrastructure/quick-deploy/aws/all-in-one/parameters.tfvars
infrastructure/quick-deploy/aws/all-in-one/variables.tf
infrastructure/quick-deploy/aws/multi-stages/armonik/main.tf
infrastructure/quick-deploy/aws/multi-stages/armonik/parameters.tfvars
infrastructure/quick-deploy/aws/multi-stages/armonik/variables.tf
infrastructure/quick-deploy/localhost/all-in-one/armonik.tf
infrastructure/quick-deploy/localhost/all-in-one/parameters.tfvars
infrastructure/quick-deploy/localhost/all-in-one/variables.tf
infrastructure/quick-deploy/localhost/multi-stages/armonik/main.tf
infrastructure/quick-deploy/localhost/multi-stages/armonik/parameters.tfvars
infrastructure/quick-deploy/localhost/multi-stages/armonik/variables.tf

feat: Add support for nginx static file

---

.docs/content/1.installation/2.windows/0.installation-using-wsl2.md
.docs/package.json
.docs/pnpm-lock.yaml

- chore: update packages
- docs: fix broken link

chore: update deps

---

.docs/content/1.installation/1.linux/0.prerequisites.md

docs: add info for scripts permissions

---

.docs/content/0.armonik/0.index.md

added visual representation of ArmoniK to the index
Unsure about the path to the svg. Please correct me if it is wrong.

docs: added diagram to index

---

.docs/content/1.installation/3.aws/aws-all-in-one-deployment.md

fixed the dead link for the variables.tf

docs: fixed links

---

infrastructure/quick-deploy/localhost/all-in-one/storage.tf
infrastructure/quick-deploy/localhost/all-in-one/variables.tf

Variabilize activemq adapter's class name and path on premise

feat: variablise activemq class name and path on premise

---

infrastructure/quick-deploy/localhost/all-in-one/storage.tf
infrastructure/quick-deploy/localhost/all-in-one/variables.tf

Reverts aneoconsulting/ArmoniK#1215

fix: "feat: variablise activemq class name and path on premise"

---

infrastructure/quick-deploy/gcp/all-in-one/monitoring.tf
infrastructure/quick-deploy/gcp/all-in-one/variables.tf
infrastructure/quick-deploy/gcp/multi-stages/monitoring/main.tf
infrastructure/quick-deploy/gcp/multi-stages/monitoring/variables.tf

fluent_bit module variables have changed in Armonik.Infra.
we need to repport it in Armonik repo

fix: fluent_bit_module_call_variable_name_fix

---

infrastructure/quick-deploy/gcp/all-in-one/outputs.tf
infrastructure/quick-deploy/gcp/multi-stages/armonik/main.tf
infrastructure/quick-deploy/gcp/multi-stages/armonik/outputs.tf

fix some missing clean about old admin gui

fix: removing_ref_to_old_admin_gui

---

infrastructure/quick-deploy/gcp/all-in-one/Makefile
infrastructure/quick-deploy/gcp/multi-stages/Makefile

for aws we have make bootstrap-deploy && make deploy-s3-of-backend
in gcp  we have to create the bucket manually
=> so I have added make file commands to create/delete it
here after is the output of those commands

feat: Add tfstate bootstrap in gcp deployment

---

infrastructure/quick-deploy/gcp/all-in-one/armonik.tf
infrastructure/quick-deploy/gcp/multi-stages/armonik/main.tf

add kms crypto key if any to pubsub

feat: add kms crypto key for pub sub

---

infrastructure/quick-deploy/gcp/multi-stages/armonik/variables.tf

A file ....../armonik/variable.tf
was missing in the previous commit cf : https://github.com/aneoconsulting/ArmoniK/pull/1247
=> fixed

fix: missing kms variable in armonik

---

CHANGELOG.md
armonik-versions.txt
infrastructure/quick-deploy/aws/all-in-one/parameters.tfvars
infrastructure/quick-deploy/aws/multi-stages/armonik/parameters.tfvars
infrastructure/quick-deploy/aws/multi-stages/ecr/parameters.tfvars
infrastructure/quick-deploy/gcp/all-in-one/parameters.tfvars
infrastructure/quick-deploy/gcp/multi-stages/armonik/parameters.tfvars
infrastructure/quick-deploy/gcp/multi-stages/gar/parameters.tfvars
infrastructure/quick-deploy/localhost/all-in-one/parameters.tfvars
infrastructure/quick-deploy/localhost/multi-stages/armonik/parameters.tfvars
versions.tfvars.json

* add variable `target_zip_path` that can be used to define the path where the zip file of the library will be unzipped

chore: Update Extensions.Csharp to 0.14.1 and Admin.Gui to 0.11.4

---

infrastructure/quick-deploy/gcp/common.tf
infrastructure/quick-deploy/gcp/gke.tf
infrastructure/quick-deploy/gcp/variables.tf

- refactor: gcp deployment remove dependency on jq and bash
- feat: optional generation of kubeconfig for GCP

feat: remove dependencies on bash and jq for GCP deployment

---

infrastructure/quick-deploy/aws/eks.tf
infrastructure/quick-deploy/aws/variables.tf
infrastructure/quick-deploy/aws/versions.tf
versions.tfvars.json

Update to support changes in https://github.com/aneoconsulting/ArmoniK.Infra/pull/186

fix: eks module update 

---

.docs/content/2.guide/1.how-to/how-to-launch-HelloWorld-Sample.md

[Include the reason behind these changes and any relevant context.]
[Provide a detailled explanation of the modifications you have made. Link any related issues.]
[When applicable, detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]
[Discuss the impact of your modifications on ArmoniK. This might include effects on performance, configuration, documentation, new dependencies, or changes in behaviour.]

docs: typo in command

---

tools/metrics/import/log_importer/README.md
tools/metrics/import/log_importer/requirements.txt
tools/metrics/import/log_importer/s3_to_seq.py

This PR is related to the work done to [export logs from localhost to an S3 bucket](https://github.com/aneoconsulting/ArmoniK.Infra/pull/187). Adding a more general script to import saved ArmoniK logs from previous runs to a Seq deployment for further analysis. 
Building on the log2seq.py script from #62, generalized it to download entire directories that you can freely specify to match the new exports.
Multiple test runs of the script.
Not applicable.
Look at README.md for addition info.

feat: Added a python script to import logs stored in an S3 bucket to Seq

---

infrastructure/quick-deploy/gcp/versions.tf

Update the hashicorp/google version 
Update the hashicorp/google version in the versions.tf file.
This version has been used by developpers lately.
[Discuss the impact of your modifications on ArmoniK. This might include effects on performance, configuration, documentation, new dependencies, or changes in behaviour.]

chore: update provider version gcp to > 4.78.0

---

infrastructure/quick-deploy/gcp/armonik.tf
infrastructure/quick-deploy/gcp/parameters.tfvars
infrastructure/quick-deploy/gcp/storage.tf
infrastructure/quick-deploy/gcp/variables.tf

The motivation is to use a non-managed service instead of Pub/Sub in GCP.
We are looking for a replacement for the Pub/Sub messaging service and use Active MQ, an open-source service message broker.
[When applicable, detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]
[Discuss the impact of your modifications on ArmoniK. This might include effects on performance, configuration, documentation, new dependencies, or changes in behaviour.]

feat: implement active mq instead of pub/sub

---

infrastructure/quick-deploy/aws/armonik.tf
infrastructure/quick-deploy/aws/parameters.tfvars
infrastructure/quick-deploy/aws/storage.tf
infrastructure/quick-deploy/aws/variables.tf
infrastructure/quick-deploy/gcp/parameters.tfvars
infrastructure/quick-deploy/gcp/storage.tf
infrastructure/quick-deploy/gcp/variables.tf
infrastructure/quick-deploy/localhost/parameters.tfvars
infrastructure/quick-deploy/localhost/storage.tf
infrastructure/quick-deploy/localhost/variables.tf
versions.tfvars.json

Include the resources and optional activemq parameters in the active mq module used.
Add the variables in the used module such as limits, requests and activemq_opts_memory.
The deployment should run successfully.
The PR will allow in developers in the future to a more customizable active mq module.
PR should be done with [feat: add resources and activemq opts memory variables in the activemq module](https://github.com/aneoconsulting/ArmoniK.Infra/pull/202)

feat: customize active mq in different environments

---

.docs/content/getting-started/installation/local.md
.docs/content/getting-started/installation/prerequisites.md
.docs/content/user-guide/how-to-use-htc-mock.md
README.md

Fix some link or markdown title .
Now every armoniK links availlable on  readthedocs instead of github.io are corrected.

docs: add new links

---

infrastructure/quick-deploy/gcp/armonik.tf
infrastructure/quick-deploy/gcp/storage.tf
versions.tfvars.json

ArmoniK components are outdated.
Update versions of ArmoniK components to their latest version.
Those versions fix some dpeloyment bugs.
Localhost, AWS, and GCP have been tested locally and are working well.

chore(deps): Update versions of ArmoniK components

---

versions.tfvars.json

[Core 0.33.1](https://github.com/aneoconsulting/ArmoniK.Core/releases/tag/0.33.1) and [Infra 0.11.0](https://github.com/aneoconsulting/ArmoniK.Infra/releases/tag/0.11.0) were released.
Upgrade versions in `versions.tfvars`.

chore: update core version

---

infrastructure/quick-deploy/aws/parameters.tfvars

Missing node selector section in pymonik partition

fix: add missing node selector section in pymonik partition

---

infrastructure/quick-deploy/aws/armonik.tf
infrastructure/quick-deploy/aws/parameters.tfvars
infrastructure/quick-deploy/aws/storage.tf
infrastructure/quick-deploy/aws/variables.tf

Include the SQS module in the aws deployment. 
Provide the SQS module in the AWS deployment folder.
[When applicable, detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]
Adding the new module of SQS in the deployment of AWS.

feat: sqs in aws deployment

---

versions.tfvars.json

ArmoniK.Infra has been released:
- https://github.com/aneoconsulting/ArmoniK.Infra/releases/tag/0.12.0
- https://github.com/aneoconsulting/ArmoniK.Infra/releases/tag/0.12.1
Upgrade the infra modules to 0.12.1
It has been successfully deployed in AWS alongside the following changes:
- https://github.com/aneoconsulting/ArmoniK/pull/1381
- https://github.com/aneoconsulting/ArmoniK/pull/1377
- https://github.com/aneoconsulting/ArmoniK/pull/1368
The version 0.12.1 brings some deployment fixes related to AWS deployment and authentication.

chore(deps): Update Infra to 0.12

---

versions.tfvars.json

Upgrade ArmoniK components to their latest versions

chore(deps): Update versions of ArmoniK Core, Ext C# and Infra

---

versions.tfvars.json

Update our dependencies with their fixes.
Updates:
- Core 0.34.0 -> 0.34.1: update dependencies to fix CVEs, create SQS queue only once or when issues
- GUI 0.14.2 -> 0.14.3: fix cancel tasks
- Ext C# 0.19.0 -> 0.19.1: fix memory leak / OOM
Pipelines on the different repos are passing.
Fix a lot of small issues.

chore: udpate ArmoniK related dependencies
